// <auto-generated />
using System;
using CookTheWeek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookTheWeek.Data.Migrations
{
    [DbContext(typeof(CookTheWeekDbContext))]
    [Migration("20240324113528_AddDefaultValueToIsCookedPropertyOfMealEntity")]
    partial class AddDefaultValueToIsCookedPropertyOfMealEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookTheWeek.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasComment("The Application User");
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.FavouriteRecipe", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User Key Identifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Recipe Key Identifier");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FavoriteRecipes", t =>
                        {
                            t.HasComment("Users` Favourite Recipes");
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Key Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientCategoryId")
                        .HasColumnType("int")
                        .HasComment("Ingredient Category Key Identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Ingredient Name");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCategoryId");

                    b.ToTable("Ingredients", t =>
                        {
                            t.HasComment("Ingredient");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientCategoryId = 2,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 2,
                            IngredientCategoryId = 2,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = 3,
                            IngredientCategoryId = 2,
                            Name = "Lamb"
                        },
                        new
                        {
                            Id = 4,
                            IngredientCategoryId = 2,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 5,
                            IngredientCategoryId = 2,
                            Name = "Goat"
                        },
                        new
                        {
                            Id = 6,
                            IngredientCategoryId = 2,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 7,
                            IngredientCategoryId = 2,
                            Name = "Rabbit"
                        },
                        new
                        {
                            Id = 8,
                            IngredientCategoryId = 2,
                            Name = "Venison"
                        },
                        new
                        {
                            Id = 9,
                            IngredientCategoryId = 2,
                            Name = "Duck"
                        },
                        new
                        {
                            Id = 10,
                            IngredientCategoryId = 2,
                            Name = "Wild Game Meat"
                        },
                        new
                        {
                            Id = 11,
                            IngredientCategoryId = 2,
                            Name = "Minced Meat"
                        },
                        new
                        {
                            Id = 31,
                            IngredientCategoryId = 2,
                            Name = "Sausage(s)"
                        },
                        new
                        {
                            Id = 32,
                            IngredientCategoryId = 2,
                            Name = "Meatboll(s)"
                        },
                        new
                        {
                            Id = 12,
                            IngredientCategoryId = 1,
                            Name = "Egg(s)"
                        },
                        new
                        {
                            Id = 13,
                            IngredientCategoryId = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 14,
                            IngredientCategoryId = 1,
                            Name = "Yogurt"
                        },
                        new
                        {
                            Id = 15,
                            IngredientCategoryId = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 16,
                            IngredientCategoryId = 1,
                            Name = "Yellow cheese"
                        },
                        new
                        {
                            Id = 17,
                            IngredientCategoryId = 1,
                            Name = "Cheddar"
                        },
                        new
                        {
                            Id = 18,
                            IngredientCategoryId = 1,
                            Name = "Brie"
                        },
                        new
                        {
                            Id = 19,
                            IngredientCategoryId = 1,
                            Name = "Feta"
                        },
                        new
                        {
                            Id = 20,
                            IngredientCategoryId = 1,
                            Name = "Camembert"
                        },
                        new
                        {
                            Id = 21,
                            IngredientCategoryId = 1,
                            Name = "Gouda"
                        },
                        new
                        {
                            Id = 22,
                            IngredientCategoryId = 1,
                            Name = "Goat Cheese"
                        },
                        new
                        {
                            Id = 23,
                            IngredientCategoryId = 1,
                            Name = "Emmental"
                        },
                        new
                        {
                            Id = 24,
                            IngredientCategoryId = 1,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 25,
                            IngredientCategoryId = 1,
                            Name = "Ricotta"
                        },
                        new
                        {
                            Id = 26,
                            IngredientCategoryId = 1,
                            Name = "Gorgonzola"
                        },
                        new
                        {
                            Id = 27,
                            IngredientCategoryId = 1,
                            Name = "Cottage Cheese"
                        },
                        new
                        {
                            Id = 28,
                            IngredientCategoryId = 1,
                            Name = "Edam"
                        },
                        new
                        {
                            Id = 29,
                            IngredientCategoryId = 1,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 30,
                            IngredientCategoryId = 1,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 33,
                            IngredientCategoryId = 3,
                            Name = "Lentils"
                        },
                        new
                        {
                            Id = 34,
                            IngredientCategoryId = 3,
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Id = 35,
                            IngredientCategoryId = 3,
                            Name = "Green Peas"
                        },
                        new
                        {
                            Id = 36,
                            IngredientCategoryId = 3,
                            Name = "White Beans"
                        },
                        new
                        {
                            Id = 37,
                            IngredientCategoryId = 3,
                            Name = "Soybeans"
                        },
                        new
                        {
                            Id = 38,
                            IngredientCategoryId = 3,
                            Name = "Mung Beans"
                        },
                        new
                        {
                            Id = 39,
                            IngredientCategoryId = 3,
                            Name = "Red Lentils"
                        },
                        new
                        {
                            Id = 40,
                            IngredientCategoryId = 3,
                            Name = "Black Beans"
                        },
                        new
                        {
                            Id = 41,
                            IngredientCategoryId = 3,
                            Name = "Edamame"
                        },
                        new
                        {
                            Id = 42,
                            IngredientCategoryId = 3,
                            Name = "Green Lentils"
                        },
                        new
                        {
                            Id = 43,
                            IngredientCategoryId = 4,
                            Name = "White Flour"
                        },
                        new
                        {
                            Id = 44,
                            IngredientCategoryId = 4,
                            Name = "Whole Wheat Flour"
                        },
                        new
                        {
                            Id = 45,
                            IngredientCategoryId = 4,
                            Name = "Rye Flour"
                        },
                        new
                        {
                            Id = 46,
                            IngredientCategoryId = 4,
                            Name = "Spelt Flour"
                        },
                        new
                        {
                            Id = 47,
                            IngredientCategoryId = 4,
                            Name = "Almond Flour"
                        },
                        new
                        {
                            Id = 48,
                            IngredientCategoryId = 13,
                            Name = "Pine Nuts"
                        },
                        new
                        {
                            Id = 49,
                            IngredientCategoryId = 4,
                            Name = "Spelled Flour"
                        },
                        new
                        {
                            Id = 50,
                            IngredientCategoryId = 4,
                            Name = "Corn Flour"
                        },
                        new
                        {
                            Id = 51,
                            IngredientCategoryId = 4,
                            Name = "Rice Flour"
                        },
                        new
                        {
                            Id = 52,
                            IngredientCategoryId = 5,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 53,
                            IngredientCategoryId = 5,
                            Name = "Black Pepper"
                        },
                        new
                        {
                            Id = 54,
                            IngredientCategoryId = 5,
                            Name = "Paprika (Red Pepper)"
                        },
                        new
                        {
                            Id = 55,
                            IngredientCategoryId = 5,
                            Name = "Turmeric"
                        },
                        new
                        {
                            Id = 56,
                            IngredientCategoryId = 5,
                            Name = "Thyme"
                        },
                        new
                        {
                            Id = 57,
                            IngredientCategoryId = 5,
                            Name = "Oregano"
                        },
                        new
                        {
                            Id = 58,
                            IngredientCategoryId = 5,
                            Name = "Rosemary"
                        },
                        new
                        {
                            Id = 59,
                            IngredientCategoryId = 5,
                            Name = "Mint"
                        },
                        new
                        {
                            Id = 60,
                            IngredientCategoryId = 5,
                            Name = "Cardamon"
                        },
                        new
                        {
                            Id = 61,
                            IngredientCategoryId = 5,
                            Name = "Curry Powder"
                        },
                        new
                        {
                            Id = 62,
                            IngredientCategoryId = 5,
                            Name = "Chilli powder"
                        },
                        new
                        {
                            Id = 63,
                            IngredientCategoryId = 5,
                            Name = "Ginger"
                        },
                        new
                        {
                            Id = 64,
                            IngredientCategoryId = 5,
                            Name = "Parsley"
                        },
                        new
                        {
                            Id = 65,
                            IngredientCategoryId = 5,
                            Name = "Bay leaf"
                        },
                        new
                        {
                            Id = 66,
                            IngredientCategoryId = 5,
                            Name = "Allspice"
                        },
                        new
                        {
                            Id = 67,
                            IngredientCategoryId = 5,
                            Name = "Basil"
                        },
                        new
                        {
                            Id = 68,
                            IngredientCategoryId = 5,
                            Name = "Clove"
                        },
                        new
                        {
                            Id = 69,
                            IngredientCategoryId = 5,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            Id = 70,
                            IngredientCategoryId = 5,
                            Name = "Vanilla"
                        },
                        new
                        {
                            Id = 71,
                            IngredientCategoryId = 5,
                            Name = "Celery"
                        },
                        new
                        {
                            Id = 72,
                            IngredientCategoryId = 5,
                            Name = "Peppermint"
                        },
                        new
                        {
                            Id = 73,
                            IngredientCategoryId = 5,
                            Name = "Marjoram"
                        },
                        new
                        {
                            Id = 74,
                            IngredientCategoryId = 5,
                            Name = "Wild Garlic"
                        },
                        new
                        {
                            Id = 75,
                            IngredientCategoryId = 5,
                            Name = "Fennel (dill)"
                        },
                        new
                        {
                            Id = 76,
                            IngredientCategoryId = 5,
                            Name = "Coriander"
                        },
                        new
                        {
                            Id = 77,
                            IngredientCategoryId = 5,
                            Name = "Clary Sage"
                        },
                        new
                        {
                            Id = 78,
                            IngredientCategoryId = 5,
                            Name = "Cilantro"
                        },
                        new
                        {
                            Id = 79,
                            IngredientCategoryId = 5,
                            Name = "Chives"
                        },
                        new
                        {
                            Id = 80,
                            IngredientCategoryId = 6,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 81,
                            IngredientCategoryId = 6,
                            Name = "Honey"
                        },
                        new
                        {
                            Id = 82,
                            IngredientCategoryId = 6,
                            Name = "Maple Syrup"
                        },
                        new
                        {
                            Id = 83,
                            IngredientCategoryId = 6,
                            Name = "Coconut Sugar"
                        },
                        new
                        {
                            Id = 84,
                            IngredientCategoryId = 6,
                            Name = "Coconut Sugar"
                        },
                        new
                        {
                            Id = 85,
                            IngredientCategoryId = 6,
                            Name = "Powdered Sugar"
                        },
                        new
                        {
                            Id = 86,
                            IngredientCategoryId = 6,
                            Name = "Brown Sugar"
                        },
                        new
                        {
                            Id = 87,
                            IngredientCategoryId = 6,
                            Name = "Molasses"
                        },
                        new
                        {
                            Id = 88,
                            IngredientCategoryId = 6,
                            Name = "Agave Syrup"
                        },
                        new
                        {
                            Id = 89,
                            IngredientCategoryId = 6,
                            Name = "Cane Sugar"
                        },
                        new
                        {
                            Id = 90,
                            IngredientCategoryId = 7,
                            Name = "Lasagna"
                        },
                        new
                        {
                            Id = 91,
                            IngredientCategoryId = 7,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 92,
                            IngredientCategoryId = 7,
                            Name = "Tagliatelle"
                        },
                        new
                        {
                            Id = 93,
                            IngredientCategoryId = 7,
                            Name = "Fusilli"
                        },
                        new
                        {
                            Id = 94,
                            IngredientCategoryId = 7,
                            Name = "Gnocchi"
                        },
                        new
                        {
                            Id = 95,
                            IngredientCategoryId = 7,
                            Name = "Macaroni"
                        },
                        new
                        {
                            Id = 96,
                            IngredientCategoryId = 7,
                            Name = "Penne"
                        },
                        new
                        {
                            Id = 97,
                            IngredientCategoryId = 7,
                            Name = "Rigatoni"
                        },
                        new
                        {
                            Id = 98,
                            IngredientCategoryId = 8,
                            Name = "Beet(s)"
                        },
                        new
                        {
                            Id = 99,
                            IngredientCategoryId = 8,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 100,
                            IngredientCategoryId = 8,
                            Name = "Brussels Sprout"
                        },
                        new
                        {
                            Id = 101,
                            IngredientCategoryId = 8,
                            Name = "Cabbage"
                        },
                        new
                        {
                            Id = 102,
                            IngredientCategoryId = 8,
                            Name = "Celery"
                        },
                        new
                        {
                            Id = 103,
                            IngredientCategoryId = 8,
                            Name = "Kale"
                        },
                        new
                        {
                            Id = 104,
                            IngredientCategoryId = 8,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 105,
                            IngredientCategoryId = 8,
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 106,
                            IngredientCategoryId = 8,
                            Name = "Asparagus"
                        },
                        new
                        {
                            Id = 107,
                            IngredientCategoryId = 8,
                            Name = "Cauliflower"
                        },
                        new
                        {
                            Id = 108,
                            IngredientCategoryId = 8,
                            Name = "Eggplant"
                        },
                        new
                        {
                            Id = 109,
                            IngredientCategoryId = 8,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 110,
                            IngredientCategoryId = 8,
                            Name = "Nettles"
                        },
                        new
                        {
                            Id = 111,
                            IngredientCategoryId = 8,
                            Name = "Leek"
                        },
                        new
                        {
                            Id = 112,
                            IngredientCategoryId = 8,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 113,
                            IngredientCategoryId = 8,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 114,
                            IngredientCategoryId = 8,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 115,
                            IngredientCategoryId = 8,
                            Name = "Celeriac"
                        },
                        new
                        {
                            Id = 116,
                            IngredientCategoryId = 8,
                            Name = "Ginger Root"
                        },
                        new
                        {
                            Id = 117,
                            IngredientCategoryId = 8,
                            Name = "Radish(es)"
                        },
                        new
                        {
                            Id = 118,
                            IngredientCategoryId = 8,
                            Name = "Potato(s)"
                        },
                        new
                        {
                            Id = 119,
                            IngredientCategoryId = 8,
                            Name = "Sweet Potato(s)"
                        },
                        new
                        {
                            Id = 120,
                            IngredientCategoryId = 8,
                            Name = "Sweet Corn"
                        },
                        new
                        {
                            Id = 121,
                            IngredientCategoryId = 8,
                            Name = "Zucchini"
                        },
                        new
                        {
                            Id = 122,
                            IngredientCategoryId = 8,
                            Name = "Tomato(s)"
                        },
                        new
                        {
                            Id = 123,
                            IngredientCategoryId = 8,
                            Name = "Cherry Tomato(s)"
                        },
                        new
                        {
                            Id = 124,
                            IngredientCategoryId = 8,
                            Name = "Green onion(s)"
                        },
                        new
                        {
                            Id = 125,
                            IngredientCategoryId = 8,
                            Name = "Cucumber(s)"
                        },
                        new
                        {
                            Id = 126,
                            IngredientCategoryId = 8,
                            Name = "Baby spinach"
                        },
                        new
                        {
                            Id = 127,
                            IngredientCategoryId = 8,
                            Name = "Red Bell Pepper"
                        },
                        new
                        {
                            Id = 128,
                            IngredientCategoryId = 8,
                            Name = "Green Bell Pepper"
                        },
                        new
                        {
                            Id = 129,
                            IngredientCategoryId = 8,
                            Name = "Red Onion(s)"
                        },
                        new
                        {
                            Id = 130,
                            IngredientCategoryId = 8,
                            Name = "Arugula"
                        },
                        new
                        {
                            Id = 131,
                            IngredientCategoryId = 8,
                            Name = "Parsnip"
                        },
                        new
                        {
                            Id = 132,
                            IngredientCategoryId = 9,
                            Name = "Apple(s)"
                        },
                        new
                        {
                            Id = 133,
                            IngredientCategoryId = 9,
                            Name = "Banana(s)"
                        },
                        new
                        {
                            Id = 134,
                            IngredientCategoryId = 9,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 135,
                            IngredientCategoryId = 9,
                            Name = "Strawberries"
                        },
                        new
                        {
                            Id = 136,
                            IngredientCategoryId = 9,
                            Name = "Pear(s)"
                        },
                        new
                        {
                            Id = 137,
                            IngredientCategoryId = 9,
                            Name = "Cherries"
                        },
                        new
                        {
                            Id = 138,
                            IngredientCategoryId = 9,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Id = 139,
                            IngredientCategoryId = 9,
                            Name = "Kiwi"
                        },
                        new
                        {
                            Id = 140,
                            IngredientCategoryId = 9,
                            Name = "Orange(s)"
                        },
                        new
                        {
                            Id = 141,
                            IngredientCategoryId = 9,
                            Name = "Lemon(s)"
                        },
                        new
                        {
                            Id = 142,
                            IngredientCategoryId = 9,
                            Name = "Grapes"
                        },
                        new
                        {
                            Id = 143,
                            IngredientCategoryId = 9,
                            Name = "Peaches"
                        },
                        new
                        {
                            Id = 144,
                            IngredientCategoryId = 9,
                            Name = "Mango"
                        },
                        new
                        {
                            Id = 145,
                            IngredientCategoryId = 9,
                            Name = "Raspberries"
                        },
                        new
                        {
                            Id = 146,
                            IngredientCategoryId = 9,
                            Name = "Blueberries"
                        },
                        new
                        {
                            Id = 147,
                            IngredientCategoryId = 9,
                            Name = "Plum(s)"
                        },
                        new
                        {
                            Id = 148,
                            IngredientCategoryId = 9,
                            Name = "Grapefruit"
                        },
                        new
                        {
                            Id = 149,
                            IngredientCategoryId = 9,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 150,
                            IngredientCategoryId = 9,
                            Name = "Prune(s)"
                        },
                        new
                        {
                            Id = 151,
                            IngredientCategoryId = 9,
                            Name = "Sour Cherries"
                        },
                        new
                        {
                            Id = 152,
                            IngredientCategoryId = 9,
                            Name = "Melon"
                        },
                        new
                        {
                            Id = 153,
                            IngredientCategoryId = 9,
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = 154,
                            IngredientCategoryId = 10,
                            Name = "Sunflower Oil"
                        },
                        new
                        {
                            Id = 155,
                            IngredientCategoryId = 10,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 156,
                            IngredientCategoryId = 10,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 157,
                            IngredientCategoryId = 10,
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 158,
                            IngredientCategoryId = 10,
                            Name = "Coconut Oil"
                        },
                        new
                        {
                            Id = 159,
                            IngredientCategoryId = 10,
                            Name = "Avocado Oil"
                        },
                        new
                        {
                            Id = 160,
                            IngredientCategoryId = 10,
                            Name = "Ghee"
                        },
                        new
                        {
                            Id = 161,
                            IngredientCategoryId = 10,
                            Name = "Lard"
                        },
                        new
                        {
                            Id = 162,
                            IngredientCategoryId = 10,
                            Name = "Mascarpone"
                        },
                        new
                        {
                            Id = 163,
                            IngredientCategoryId = 10,
                            Name = "Sour Cream"
                        },
                        new
                        {
                            Id = 164,
                            IngredientCategoryId = 10,
                            Name = "Whipped Cream"
                        },
                        new
                        {
                            Id = 165,
                            IngredientCategoryId = 10,
                            Name = "Coconut Cream"
                        },
                        new
                        {
                            Id = 167,
                            IngredientCategoryId = 10,
                            Name = "Diary Free Cream"
                        },
                        new
                        {
                            Id = 168,
                            IngredientCategoryId = 10,
                            Name = "Sesame Oil"
                        },
                        new
                        {
                            Id = 169,
                            IngredientCategoryId = 11,
                            Name = "Trout"
                        },
                        new
                        {
                            Id = 170,
                            IngredientCategoryId = 11,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 171,
                            IngredientCategoryId = 11,
                            Name = "Tuna"
                        },
                        new
                        {
                            Id = 172,
                            IngredientCategoryId = 11,
                            Name = "Sardines"
                        },
                        new
                        {
                            Id = 173,
                            IngredientCategoryId = 11,
                            Name = "Mackerel"
                        },
                        new
                        {
                            Id = 174,
                            IngredientCategoryId = 11,
                            Name = "Cod"
                        },
                        new
                        {
                            Id = 175,
                            IngredientCategoryId = 11,
                            Name = "Mussels"
                        },
                        new
                        {
                            Id = 176,
                            IngredientCategoryId = 11,
                            Name = "Skip Jack"
                        },
                        new
                        {
                            Id = 177,
                            IngredientCategoryId = 11,
                            Name = "Shark"
                        },
                        new
                        {
                            Id = 178,
                            IngredientCategoryId = 11,
                            Name = "Shark"
                        },
                        new
                        {
                            Id = 179,
                            IngredientCategoryId = 11,
                            Name = "Silver Catfish (Pangasius)"
                        },
                        new
                        {
                            Id = 180,
                            IngredientCategoryId = 11,
                            Name = "Octopus"
                        },
                        new
                        {
                            Id = 181,
                            IngredientCategoryId = 11,
                            Name = "Squids"
                        },
                        new
                        {
                            Id = 182,
                            IngredientCategoryId = 11,
                            Name = "Hake fish"
                        },
                        new
                        {
                            Id = 183,
                            IngredientCategoryId = 11,
                            Name = "Salmon Trout"
                        },
                        new
                        {
                            Id = 184,
                            IngredientCategoryId = 11,
                            Name = "Sprat"
                        },
                        new
                        {
                            Id = 185,
                            IngredientCategoryId = 11,
                            Name = "Sardines"
                        },
                        new
                        {
                            Id = 186,
                            IngredientCategoryId = 12,
                            Name = "Lemon Juice"
                        },
                        new
                        {
                            Id = 187,
                            IngredientCategoryId = 12,
                            Name = "Tomatoe Paste"
                        },
                        new
                        {
                            Id = 188,
                            IngredientCategoryId = 12,
                            Name = "Mustard"
                        },
                        new
                        {
                            Id = 189,
                            IngredientCategoryId = 5,
                            Name = "Savory"
                        },
                        new
                        {
                            Id = 221,
                            IngredientCategoryId = 7,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 222,
                            IngredientCategoryId = 7,
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = 192,
                            IngredientCategoryId = 7,
                            Name = "Black Rice"
                        },
                        new
                        {
                            Id = 193,
                            IngredientCategoryId = 7,
                            Name = "Barley"
                        },
                        new
                        {
                            Id = 194,
                            IngredientCategoryId = 7,
                            Name = "Bulgur"
                        },
                        new
                        {
                            Id = 195,
                            IngredientCategoryId = 7,
                            Name = "Quinoa"
                        },
                        new
                        {
                            Id = 196,
                            IngredientCategoryId = 7,
                            Name = "Amaranth"
                        },
                        new
                        {
                            Id = 197,
                            IngredientCategoryId = 7,
                            Name = "Oats"
                        },
                        new
                        {
                            Id = 198,
                            IngredientCategoryId = 7,
                            Name = "Oatmeal"
                        },
                        new
                        {
                            Id = 199,
                            IngredientCategoryId = 13,
                            Name = "Chia Seeds"
                        },
                        new
                        {
                            Id = 200,
                            IngredientCategoryId = 7,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 201,
                            IngredientCategoryId = 7,
                            Name = "Corn"
                        },
                        new
                        {
                            Id = 202,
                            IngredientCategoryId = 7,
                            Name = "Spelt"
                        },
                        new
                        {
                            Id = 203,
                            IngredientCategoryId = 7,
                            Name = "Buckwheat"
                        },
                        new
                        {
                            Id = 204,
                            IngredientCategoryId = 7,
                            Name = "Millet"
                        },
                        new
                        {
                            Id = 205,
                            IngredientCategoryId = 7,
                            Name = "Farro"
                        },
                        new
                        {
                            Id = 206,
                            IngredientCategoryId = 13,
                            Name = "Almonds"
                        },
                        new
                        {
                            Id = 207,
                            IngredientCategoryId = 13,
                            Name = "Brazil Nuts"
                        },
                        new
                        {
                            Id = 208,
                            IngredientCategoryId = 13,
                            Name = "Cashew Nuts"
                        },
                        new
                        {
                            Id = 209,
                            IngredientCategoryId = 13,
                            Name = "Hazel Nuts"
                        },
                        new
                        {
                            Id = 210,
                            IngredientCategoryId = 13,
                            Name = "Macadamias"
                        },
                        new
                        {
                            Id = 211,
                            IngredientCategoryId = 13,
                            Name = "Pecans"
                        },
                        new
                        {
                            Id = 212,
                            IngredientCategoryId = 13,
                            Name = "Pistachios"
                        },
                        new
                        {
                            Id = 213,
                            IngredientCategoryId = 13,
                            Name = "Walnuts"
                        },
                        new
                        {
                            Id = 214,
                            IngredientCategoryId = 13,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 215,
                            IngredientCategoryId = 13,
                            Name = "Pumpkin Seeds"
                        },
                        new
                        {
                            Id = 216,
                            IngredientCategoryId = 13,
                            Name = "Flax Seeds"
                        },
                        new
                        {
                            Id = 217,
                            IngredientCategoryId = 13,
                            Name = "Sesame Seeds"
                        },
                        new
                        {
                            Id = 218,
                            IngredientCategoryId = 13,
                            Name = "Poppy Seeds"
                        },
                        new
                        {
                            Id = 219,
                            IngredientCategoryId = 13,
                            Name = "Sunflower Seeds"
                        },
                        new
                        {
                            Id = 220,
                            IngredientCategoryId = 13,
                            Name = "Psyllium Seeds"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Key identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Ingredient Category Name");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategories", t =>
                        {
                            t.HasComment("Ingredients Category");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eggs, Milk and Diary products"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meat, Ground Meat and Sausage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beans, Lentils and Legumes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flour and Baking Products"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Herbs and Spices"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sweeteners"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pasta and Grains"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fats and Oils"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fish and Seafood"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Others"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nuts and seeds"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Meal Key Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CookDate")
                        .HasColumnType("datetime2")
                        .HasComment("Meal Cook Date");

                    b.Property<bool>("IsCooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Recipe is cooked or not");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Recipe Key Identifier");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int")
                        .HasComment("Meal Serving Size");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Meals", t =>
                        {
                            t.HasComment("A Meal is a Recipe with user-defined Serving Size and Cook Date");
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Key Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Measure Name");

                    b.HasKey("Id");

                    b.ToTable("Measures", t =>
                        {
                            t.HasComment("The Measure of the Recipe Ingredient");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "piece(s)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "clove(s)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ml"
                        },
                        new
                        {
                            Id = 4,
                            Name = "l"
                        },
                        new
                        {
                            Id = 5,
                            Name = "g"
                        },
                        new
                        {
                            Id = 6,
                            Name = "kg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "tsp"
                        },
                        new
                        {
                            Id = 8,
                            Name = "tbsp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "cup"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Key Indetifier");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Recipe Date and Time Creation");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Recipe Description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Recipe Image Link");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Recipe Instructions");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Soft Delete for Recipe");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Creator of the recipe");

                    b.Property<int>("RecipeCategoryId")
                        .HasColumnType("int")
                        .HasComment("Recipe Category Key Identifier");

                    b.Property<int>("Servings")
                        .HasColumnType("int")
                        .HasComment("Recipe Serving Size");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Recipe Title");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("time")
                        .HasComment("Recipe Cooking Time");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasComment("Recipe");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Мусака! Царицата на българската кухня! Едно от най-обичаните и най-често приготвяните ястия. Мусаката е абсолютният любимец както на всеки българин, така и на чужденците. Ако се притеснявате какво да сготвите на гостите от чужбина, можете да заложите на мусаката. Чуждестранните гости едва ли ще харесат таратора и едва ли ще съберат сили да пробват печените чушки с доматен сос, но мусаката задължително ще спечели доверието им, ще си оближат пръстите и ще искат порция допълнително. Рецептите за мусака нямат много вариации, вариантите са основно в приготвянето на заливката. Предложената тук рецепта за мусака е класическа, лесна и подходяща и за по-неопитните готвачи.",
                            ImageUrl = "https://www.supichka.com/files/images/1242/fit_1400_933.jpg",
                            Instructions = "Загрявате мазнината в дълбок тиган или тенджера. В загрятата мазнина задушете измитият, изчистен и нарязан на дребно лук, докато омекне. Добавяте нарязаните на дребно половината домати и каймата, черният пипер и чубрицата, както и една чаена лъжица сол. Може да ползвате кайма, каквато имате под ръка, но най-вкусната мусаката става с кайма смес – 50% свинско и 50 % телешко месо.\r\nСлед като водата от доматите изври добавяте червения пипер. Измивате, почиствате, обелвате и нарязвате на дребни кубчета картофите и ги прибавяте към месото. Намазнявате тавичка на дъното на която поставяте другата половина от доматите и върху тях изсипвате сместа за мусака. Добавяте една непълна чаена чаша гореща вода и поставяте в предварително загрята на 200 градуса фурна. Печете до докато водата изври, а картофите станат златисти.\r\nИдва моментът за приготвяне на заливката за мусаката. Тя става лесно и много бързо. Разбърквате киселото мляко и яйцата, след което при постоянно бъркане добавяте и брашното, до получаване на гладка смес. Накрая добавяте и настъргания на дребно кашкавал. Заливате мусаката и печете докато порозовее.",
                            IsDeleted = false,
                            OwnerId = "92E86642-3F6F-4949-BACB-DE0EF010E36D",
                            RecipeCategoryId = 4,
                            Servings = 8,
                            Title = "Мусака",
                            TotalTime = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Key Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Recipe Category Name");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories", t =>
                        {
                            t.HasComment("Recipes Category");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Main Dish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Appetizer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Key Identifier for Recipe");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasComment("Key Identifier for Ingredient");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int")
                        .HasComment("Measure Key Identifier");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Quantity of the Ingredient in this Recipe");

                    b.Property<int?>("SpecificationId")
                        .HasColumnType("int")
                        .HasComment("Specification Key Identifier");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("RecipesIngredients", t =>
                        {
                            t.HasComment("The Ingredients in Recipe");
                        });

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 11,
                            MeasureId = 5,
                            Qty = 500m
                        },
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 113,
                            MeasureId = 1,
                            Qty = 2m
                        },
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 118,
                            MeasureId = 6,
                            Qty = 1m
                        },
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 122,
                            MeasureId = 5,
                            Qty = 250m
                        },
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 154,
                            MeasureId = 8,
                            Qty = 3m
                        },
                        new
                        {
                            RecipeId = new Guid("377a3703-e719-42db-b013-19e5bd23892a"),
                            IngredientId = 54,
                            MeasureId = 8,
                            Qty = 1m
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Specification Key Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Specification Description");

                    b.HasKey("Id");

                    b.ToTable("Specifications", t =>
                        {
                            t.HasComment("The Specification of the Recipe Ingredient");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "frozen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "canned"
                        },
                        new
                        {
                            Id = 3,
                            Description = "sliced"
                        },
                        new
                        {
                            Id = 4,
                            Description = "pre-cooked"
                        },
                        new
                        {
                            Id = 5,
                            Description = "grated"
                        },
                        new
                        {
                            Id = 6,
                            Description = "fermented"
                        },
                        new
                        {
                            Id = 7,
                            Description = "blended"
                        },
                        new
                        {
                            Id = 8,
                            Description = "finely-chopped"
                        },
                        new
                        {
                            Id = 9,
                            Description = "fresh"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.FavouriteRecipe", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.Recipe", "Recipe")
                        .WithMany("FavouriteRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", "User")
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Ingredient", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.IngredientCategory", "IngredientCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientCategory");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Meal", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Recipe", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.RecipeCategory", "RecipeCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipeCategory");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.Ingredient", "Ingredient")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.Recipe", "Recipe")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.Specification", "Specification")
                        .WithMany()
                        .HasForeignKey("SpecificationId");

                    b.Navigation("Ingredient");

                    b.Navigation("Measure");

                    b.Navigation("Recipe");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FavoriteRecipes");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Ingredient", b =>
                {
                    b.Navigation("RecipesIngredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Recipe", b =>
                {
                    b.Navigation("FavouriteRecipes");

                    b.Navigation("RecipesIngredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeCategory", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
