// <auto-generated />
using System;
using CookTheWeek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookTheWeek.Data.Migrations
{
    [DbContext(typeof(CookTheWeekDbContext))]
    [Migration("20240222135744_UpdateMeasureInRecipeIngredient")]
    partial class UpdateMeasureInRecipeIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookTheWeek.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IgredientEntities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCategoryId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientCategoryId = 2,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 2,
                            IngredientCategoryId = 2,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = 3,
                            IngredientCategoryId = 2,
                            Name = "Lamb"
                        },
                        new
                        {
                            Id = 4,
                            IngredientCategoryId = 2,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 5,
                            IngredientCategoryId = 2,
                            Name = "Goat"
                        },
                        new
                        {
                            Id = 6,
                            IngredientCategoryId = 2,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 7,
                            IngredientCategoryId = 2,
                            Name = "Rabbit"
                        },
                        new
                        {
                            Id = 8,
                            IngredientCategoryId = 2,
                            Name = "Venison"
                        },
                        new
                        {
                            Id = 9,
                            IngredientCategoryId = 2,
                            Name = "Duck"
                        },
                        new
                        {
                            Id = 10,
                            IngredientCategoryId = 2,
                            Name = "Wild Game Meat"
                        },
                        new
                        {
                            Id = 11,
                            IngredientCategoryId = 2,
                            Name = "Minced Meat"
                        },
                        new
                        {
                            Id = 31,
                            IngredientCategoryId = 2,
                            Name = "Sausage(s)"
                        },
                        new
                        {
                            Id = 32,
                            IngredientCategoryId = 2,
                            Name = "Meatboll(s)"
                        },
                        new
                        {
                            Id = 12,
                            IngredientCategoryId = 1,
                            Name = "Egg(s)"
                        },
                        new
                        {
                            Id = 13,
                            IngredientCategoryId = 1,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 14,
                            IngredientCategoryId = 1,
                            Name = "Yogurt"
                        },
                        new
                        {
                            Id = 15,
                            IngredientCategoryId = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 16,
                            IngredientCategoryId = 1,
                            Name = "Yellow cheese"
                        },
                        new
                        {
                            Id = 17,
                            IngredientCategoryId = 1,
                            Name = "Cheddar"
                        },
                        new
                        {
                            Id = 18,
                            IngredientCategoryId = 1,
                            Name = "Brie"
                        },
                        new
                        {
                            Id = 19,
                            IngredientCategoryId = 1,
                            Name = "Feta"
                        },
                        new
                        {
                            Id = 20,
                            IngredientCategoryId = 1,
                            Name = "Camembert"
                        },
                        new
                        {
                            Id = 21,
                            IngredientCategoryId = 1,
                            Name = "Gouda"
                        },
                        new
                        {
                            Id = 22,
                            IngredientCategoryId = 1,
                            Name = "Goat Cheese"
                        },
                        new
                        {
                            Id = 23,
                            IngredientCategoryId = 1,
                            Name = "Emmental"
                        },
                        new
                        {
                            Id = 24,
                            IngredientCategoryId = 1,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 25,
                            IngredientCategoryId = 1,
                            Name = "Ricotta"
                        },
                        new
                        {
                            Id = 26,
                            IngredientCategoryId = 1,
                            Name = "Gorgonzola"
                        },
                        new
                        {
                            Id = 27,
                            IngredientCategoryId = 1,
                            Name = "Cottage Cheese"
                        },
                        new
                        {
                            Id = 28,
                            IngredientCategoryId = 1,
                            Name = "Edam"
                        },
                        new
                        {
                            Id = 29,
                            IngredientCategoryId = 1,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 30,
                            IngredientCategoryId = 1,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 33,
                            IngredientCategoryId = 3,
                            Name = "Lentils"
                        },
                        new
                        {
                            Id = 34,
                            IngredientCategoryId = 3,
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Id = 35,
                            IngredientCategoryId = 3,
                            Name = "Green Peas"
                        },
                        new
                        {
                            Id = 36,
                            IngredientCategoryId = 3,
                            Name = "White Beans"
                        },
                        new
                        {
                            Id = 37,
                            IngredientCategoryId = 3,
                            Name = "Soybeans"
                        },
                        new
                        {
                            Id = 38,
                            IngredientCategoryId = 3,
                            Name = "Mung Beans"
                        },
                        new
                        {
                            Id = 39,
                            IngredientCategoryId = 3,
                            Name = "Red Lentils"
                        },
                        new
                        {
                            Id = 40,
                            IngredientCategoryId = 3,
                            Name = "Black Beans"
                        },
                        new
                        {
                            Id = 41,
                            IngredientCategoryId = 3,
                            Name = "Edamame"
                        },
                        new
                        {
                            Id = 42,
                            IngredientCategoryId = 3,
                            Name = "Green Lentils"
                        },
                        new
                        {
                            Id = 43,
                            IngredientCategoryId = 4,
                            Name = "White Flour"
                        },
                        new
                        {
                            Id = 44,
                            IngredientCategoryId = 4,
                            Name = "Whole Wheat Flour"
                        },
                        new
                        {
                            Id = 45,
                            IngredientCategoryId = 4,
                            Name = "Rye Flour"
                        },
                        new
                        {
                            Id = 46,
                            IngredientCategoryId = 4,
                            Name = "Spelt Flour"
                        },
                        new
                        {
                            Id = 47,
                            IngredientCategoryId = 4,
                            Name = "Almond Flour"
                        },
                        new
                        {
                            Id = 48,
                            IngredientCategoryId = 4,
                            Name = "Almond Flour"
                        },
                        new
                        {
                            Id = 49,
                            IngredientCategoryId = 4,
                            Name = "Spelled Flour"
                        },
                        new
                        {
                            Id = 50,
                            IngredientCategoryId = 4,
                            Name = "Corn Flour"
                        },
                        new
                        {
                            Id = 51,
                            IngredientCategoryId = 4,
                            Name = "Rice Flour"
                        },
                        new
                        {
                            Id = 52,
                            IngredientCategoryId = 5,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 53,
                            IngredientCategoryId = 5,
                            Name = "Black Pepper"
                        },
                        new
                        {
                            Id = 54,
                            IngredientCategoryId = 5,
                            Name = "Paprika (Red Pepper)"
                        },
                        new
                        {
                            Id = 55,
                            IngredientCategoryId = 5,
                            Name = "Turmeric"
                        },
                        new
                        {
                            Id = 56,
                            IngredientCategoryId = 5,
                            Name = "Thyme"
                        },
                        new
                        {
                            Id = 57,
                            IngredientCategoryId = 5,
                            Name = "Oregano"
                        },
                        new
                        {
                            Id = 58,
                            IngredientCategoryId = 5,
                            Name = "Rosemary"
                        },
                        new
                        {
                            Id = 59,
                            IngredientCategoryId = 5,
                            Name = "Mint"
                        },
                        new
                        {
                            Id = 60,
                            IngredientCategoryId = 5,
                            Name = "Cardamon"
                        },
                        new
                        {
                            Id = 61,
                            IngredientCategoryId = 5,
                            Name = "Curry Powder"
                        },
                        new
                        {
                            Id = 62,
                            IngredientCategoryId = 5,
                            Name = "Chilli powder"
                        },
                        new
                        {
                            Id = 63,
                            IngredientCategoryId = 5,
                            Name = "Ginger"
                        },
                        new
                        {
                            Id = 64,
                            IngredientCategoryId = 5,
                            Name = "Parsley"
                        },
                        new
                        {
                            Id = 65,
                            IngredientCategoryId = 5,
                            Name = "Bay leaf"
                        },
                        new
                        {
                            Id = 66,
                            IngredientCategoryId = 5,
                            Name = "Allspice"
                        },
                        new
                        {
                            Id = 67,
                            IngredientCategoryId = 5,
                            Name = "Basil"
                        },
                        new
                        {
                            Id = 68,
                            IngredientCategoryId = 5,
                            Name = "Clove"
                        },
                        new
                        {
                            Id = 69,
                            IngredientCategoryId = 5,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            Id = 70,
                            IngredientCategoryId = 5,
                            Name = "Vanilla"
                        },
                        new
                        {
                            Id = 71,
                            IngredientCategoryId = 5,
                            Name = "Celery"
                        },
                        new
                        {
                            Id = 72,
                            IngredientCategoryId = 5,
                            Name = "Peppermint"
                        },
                        new
                        {
                            Id = 73,
                            IngredientCategoryId = 5,
                            Name = "Marjoram"
                        },
                        new
                        {
                            Id = 74,
                            IngredientCategoryId = 5,
                            Name = "Wild Garlic"
                        },
                        new
                        {
                            Id = 75,
                            IngredientCategoryId = 5,
                            Name = "Fennel (dill)"
                        },
                        new
                        {
                            Id = 76,
                            IngredientCategoryId = 5,
                            Name = "Coriander"
                        },
                        new
                        {
                            Id = 77,
                            IngredientCategoryId = 5,
                            Name = "Clary Sage"
                        },
                        new
                        {
                            Id = 78,
                            IngredientCategoryId = 5,
                            Name = "Cilantro"
                        },
                        new
                        {
                            Id = 79,
                            IngredientCategoryId = 5,
                            Name = "Chives"
                        },
                        new
                        {
                            Id = 80,
                            IngredientCategoryId = 6,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 81,
                            IngredientCategoryId = 6,
                            Name = "Honey"
                        },
                        new
                        {
                            Id = 82,
                            IngredientCategoryId = 6,
                            Name = "Maple Syrup"
                        },
                        new
                        {
                            Id = 83,
                            IngredientCategoryId = 6,
                            Name = "Coconut Sugar"
                        },
                        new
                        {
                            Id = 84,
                            IngredientCategoryId = 6,
                            Name = "Coconut Sugar"
                        },
                        new
                        {
                            Id = 85,
                            IngredientCategoryId = 6,
                            Name = "Powdered Sugar"
                        },
                        new
                        {
                            Id = 86,
                            IngredientCategoryId = 6,
                            Name = "Brown Sugar"
                        },
                        new
                        {
                            Id = 87,
                            IngredientCategoryId = 6,
                            Name = "Molasses"
                        },
                        new
                        {
                            Id = 88,
                            IngredientCategoryId = 6,
                            Name = "Agave Syrup"
                        },
                        new
                        {
                            Id = 89,
                            IngredientCategoryId = 6,
                            Name = "Cane Sugar"
                        },
                        new
                        {
                            Id = 90,
                            IngredientCategoryId = 7,
                            Name = "Lasagna"
                        },
                        new
                        {
                            Id = 91,
                            IngredientCategoryId = 7,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 92,
                            IngredientCategoryId = 7,
                            Name = "Tagliatelle"
                        },
                        new
                        {
                            Id = 93,
                            IngredientCategoryId = 7,
                            Name = "Fusilli"
                        },
                        new
                        {
                            Id = 94,
                            IngredientCategoryId = 7,
                            Name = "Gnocchi"
                        },
                        new
                        {
                            Id = 95,
                            IngredientCategoryId = 7,
                            Name = "Macaroni"
                        },
                        new
                        {
                            Id = 96,
                            IngredientCategoryId = 7,
                            Name = "Penne"
                        },
                        new
                        {
                            Id = 97,
                            IngredientCategoryId = 7,
                            Name = "Rigatoni"
                        },
                        new
                        {
                            Id = 98,
                            IngredientCategoryId = 8,
                            Name = "Beet(s)"
                        },
                        new
                        {
                            Id = 99,
                            IngredientCategoryId = 8,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 100,
                            IngredientCategoryId = 8,
                            Name = "Brussels Sprout"
                        },
                        new
                        {
                            Id = 101,
                            IngredientCategoryId = 8,
                            Name = "Cabbage"
                        },
                        new
                        {
                            Id = 102,
                            IngredientCategoryId = 8,
                            Name = "Celery"
                        },
                        new
                        {
                            Id = 103,
                            IngredientCategoryId = 8,
                            Name = "Kale"
                        },
                        new
                        {
                            Id = 104,
                            IngredientCategoryId = 8,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 105,
                            IngredientCategoryId = 8,
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 106,
                            IngredientCategoryId = 8,
                            Name = "Asparagus"
                        },
                        new
                        {
                            Id = 107,
                            IngredientCategoryId = 8,
                            Name = "Cauliflower"
                        },
                        new
                        {
                            Id = 108,
                            IngredientCategoryId = 8,
                            Name = "Eggplant"
                        },
                        new
                        {
                            Id = 109,
                            IngredientCategoryId = 8,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 110,
                            IngredientCategoryId = 8,
                            Name = "Nettles"
                        },
                        new
                        {
                            Id = 111,
                            IngredientCategoryId = 8,
                            Name = "Leek"
                        },
                        new
                        {
                            Id = 112,
                            IngredientCategoryId = 8,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 113,
                            IngredientCategoryId = 8,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 114,
                            IngredientCategoryId = 8,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 115,
                            IngredientCategoryId = 8,
                            Name = "Celeriac"
                        },
                        new
                        {
                            Id = 116,
                            IngredientCategoryId = 8,
                            Name = "Ginger Root"
                        },
                        new
                        {
                            Id = 117,
                            IngredientCategoryId = 8,
                            Name = "Radish(es)"
                        },
                        new
                        {
                            Id = 118,
                            IngredientCategoryId = 8,
                            Name = "Potato(s)"
                        },
                        new
                        {
                            Id = 119,
                            IngredientCategoryId = 8,
                            Name = "Sweet Potato(s)"
                        },
                        new
                        {
                            Id = 120,
                            IngredientCategoryId = 8,
                            Name = "Sweet Corn"
                        },
                        new
                        {
                            Id = 121,
                            IngredientCategoryId = 8,
                            Name = "Zucchini"
                        },
                        new
                        {
                            Id = 122,
                            IngredientCategoryId = 8,
                            Name = "Tomato(s)"
                        },
                        new
                        {
                            Id = 123,
                            IngredientCategoryId = 8,
                            Name = "Cherry Tomato(s)"
                        },
                        new
                        {
                            Id = 124,
                            IngredientCategoryId = 8,
                            Name = "Green onion(s)"
                        },
                        new
                        {
                            Id = 125,
                            IngredientCategoryId = 8,
                            Name = "Cucumber(s)"
                        },
                        new
                        {
                            Id = 126,
                            IngredientCategoryId = 8,
                            Name = "Baby spinach"
                        },
                        new
                        {
                            Id = 127,
                            IngredientCategoryId = 8,
                            Name = "Red Bell Pepper"
                        },
                        new
                        {
                            Id = 128,
                            IngredientCategoryId = 8,
                            Name = "Green Bell Pepper"
                        },
                        new
                        {
                            Id = 129,
                            IngredientCategoryId = 8,
                            Name = "Red Onion(s)"
                        },
                        new
                        {
                            Id = 130,
                            IngredientCategoryId = 8,
                            Name = "Arugula"
                        },
                        new
                        {
                            Id = 131,
                            IngredientCategoryId = 8,
                            Name = "Parsnip"
                        },
                        new
                        {
                            Id = 132,
                            IngredientCategoryId = 9,
                            Name = "Apple(s)"
                        },
                        new
                        {
                            Id = 133,
                            IngredientCategoryId = 9,
                            Name = "Banana(s)"
                        },
                        new
                        {
                            Id = 134,
                            IngredientCategoryId = 9,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 135,
                            IngredientCategoryId = 9,
                            Name = "Strawberries"
                        },
                        new
                        {
                            Id = 136,
                            IngredientCategoryId = 9,
                            Name = "Pear(s)"
                        },
                        new
                        {
                            Id = 137,
                            IngredientCategoryId = 9,
                            Name = "Cherries"
                        },
                        new
                        {
                            Id = 138,
                            IngredientCategoryId = 9,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Id = 139,
                            IngredientCategoryId = 9,
                            Name = "Kiwi"
                        },
                        new
                        {
                            Id = 140,
                            IngredientCategoryId = 9,
                            Name = "Orange(s)"
                        },
                        new
                        {
                            Id = 141,
                            IngredientCategoryId = 9,
                            Name = "Lemon(s)"
                        },
                        new
                        {
                            Id = 142,
                            IngredientCategoryId = 9,
                            Name = "Grapes"
                        },
                        new
                        {
                            Id = 143,
                            IngredientCategoryId = 9,
                            Name = "Peaches"
                        },
                        new
                        {
                            Id = 144,
                            IngredientCategoryId = 9,
                            Name = "Mango"
                        },
                        new
                        {
                            Id = 145,
                            IngredientCategoryId = 9,
                            Name = "Raspberries"
                        },
                        new
                        {
                            Id = 146,
                            IngredientCategoryId = 9,
                            Name = "Blueberries"
                        },
                        new
                        {
                            Id = 147,
                            IngredientCategoryId = 9,
                            Name = "Plum(s)"
                        },
                        new
                        {
                            Id = 148,
                            IngredientCategoryId = 9,
                            Name = "Grapefruit"
                        },
                        new
                        {
                            Id = 149,
                            IngredientCategoryId = 9,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 150,
                            IngredientCategoryId = 9,
                            Name = "Prune(s)"
                        },
                        new
                        {
                            Id = 151,
                            IngredientCategoryId = 9,
                            Name = "Sour Cherries"
                        },
                        new
                        {
                            Id = 152,
                            IngredientCategoryId = 9,
                            Name = "Melon"
                        },
                        new
                        {
                            Id = 153,
                            IngredientCategoryId = 9,
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = 154,
                            IngredientCategoryId = 10,
                            Name = "Sunflower Oil"
                        },
                        new
                        {
                            Id = 155,
                            IngredientCategoryId = 10,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 156,
                            IngredientCategoryId = 10,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 157,
                            IngredientCategoryId = 10,
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 158,
                            IngredientCategoryId = 10,
                            Name = "Coconut Oil"
                        },
                        new
                        {
                            Id = 159,
                            IngredientCategoryId = 10,
                            Name = "Avocado Oil"
                        },
                        new
                        {
                            Id = 160,
                            IngredientCategoryId = 10,
                            Name = "Ghee"
                        },
                        new
                        {
                            Id = 161,
                            IngredientCategoryId = 10,
                            Name = "Lard"
                        },
                        new
                        {
                            Id = 162,
                            IngredientCategoryId = 10,
                            Name = "Mascarpone"
                        },
                        new
                        {
                            Id = 163,
                            IngredientCategoryId = 10,
                            Name = "Sour Cream"
                        },
                        new
                        {
                            Id = 164,
                            IngredientCategoryId = 10,
                            Name = "Whipped Cream"
                        },
                        new
                        {
                            Id = 165,
                            IngredientCategoryId = 10,
                            Name = "Coconut Cream"
                        },
                        new
                        {
                            Id = 167,
                            IngredientCategoryId = 10,
                            Name = "Diary Free Cream"
                        },
                        new
                        {
                            Id = 168,
                            IngredientCategoryId = 10,
                            Name = "Sesame Oil"
                        },
                        new
                        {
                            Id = 169,
                            IngredientCategoryId = 11,
                            Name = "Trout"
                        },
                        new
                        {
                            Id = 170,
                            IngredientCategoryId = 11,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 171,
                            IngredientCategoryId = 11,
                            Name = "Tuna"
                        },
                        new
                        {
                            Id = 172,
                            IngredientCategoryId = 11,
                            Name = "Sardines"
                        },
                        new
                        {
                            Id = 173,
                            IngredientCategoryId = 11,
                            Name = "Mackerel"
                        },
                        new
                        {
                            Id = 174,
                            IngredientCategoryId = 11,
                            Name = "Cod"
                        },
                        new
                        {
                            Id = 175,
                            IngredientCategoryId = 11,
                            Name = "Mussels"
                        },
                        new
                        {
                            Id = 176,
                            IngredientCategoryId = 11,
                            Name = "Skip Jack"
                        },
                        new
                        {
                            Id = 177,
                            IngredientCategoryId = 11,
                            Name = "Shark"
                        },
                        new
                        {
                            Id = 178,
                            IngredientCategoryId = 11,
                            Name = "Shark"
                        },
                        new
                        {
                            Id = 179,
                            IngredientCategoryId = 11,
                            Name = "Silver Catfish (Pangasius)"
                        },
                        new
                        {
                            Id = 180,
                            IngredientCategoryId = 11,
                            Name = "Octopus"
                        },
                        new
                        {
                            Id = 181,
                            IngredientCategoryId = 11,
                            Name = "Squids"
                        },
                        new
                        {
                            Id = 182,
                            IngredientCategoryId = 11,
                            Name = "Hake fish"
                        },
                        new
                        {
                            Id = 183,
                            IngredientCategoryId = 11,
                            Name = "Salmon Trout"
                        },
                        new
                        {
                            Id = 184,
                            IngredientCategoryId = 11,
                            Name = "Sprat"
                        },
                        new
                        {
                            Id = 185,
                            IngredientCategoryId = 11,
                            Name = "Sardines"
                        },
                        new
                        {
                            Id = 186,
                            IngredientCategoryId = 12,
                            Name = "Lemon Juice"
                        },
                        new
                        {
                            Id = 187,
                            IngredientCategoryId = 12,
                            Name = "Tomatoe Paste"
                        },
                        new
                        {
                            Id = 188,
                            IngredientCategoryId = 12,
                            Name = "Mustard"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IgredientEntities.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eggs, Milk and Diary products"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meat, Ground Meat and Sausage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beans, Lentils and Legumes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flour and Baking Products"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Herbs and Spices"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sweeteners"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fats and Oils"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fish and Seafood"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Measures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "piece(s)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "clove(s)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ml"
                        },
                        new
                        {
                            Id = 4,
                            Name = "l"
                        },
                        new
                        {
                            Id = 5,
                            Name = "g"
                        },
                        new
                        {
                            Id = 6,
                            Name = "kg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "tsp"
                        },
                        new
                        {
                            Id = 8,
                            Name = "tbsp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "cup"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeEntities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeEntities.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Main Dish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Appetizer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Ключ рецепта");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasComment("Ключ съставка");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int")
                        .HasComment("Мерна единица за съставка в рецепта");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Количество на съставка в рецепта");

                    b.Property<int?>("SpecificationId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("RecipesIngredients", t =>
                        {
                            t.HasComment("Съставки към рецепти");
                        });
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "frozen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "canned"
                        },
                        new
                        {
                            Id = 3,
                            Description = "sliced"
                        },
                        new
                        {
                            Id = 4,
                            Description = "pre-cooked"
                        },
                        new
                        {
                            Id = 5,
                            Description = "grated"
                        },
                        new
                        {
                            Id = 6,
                            Description = "fermented"
                        },
                        new
                        {
                            Id = 7,
                            Description = "blended"
                        },
                        new
                        {
                            Id = 8,
                            Description = "finely-chopped"
                        },
                        new
                        {
                            Id = 9,
                            Description = "fresh"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IgredientEntities.Ingredient", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.IgredientEntities.IngredientCategory", "IngredientCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientCategory");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeEntities.Recipe", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CookTheWeek.Data.Models.RecipeEntities.RecipeCategory", "RecipeCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipeCategory");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.IgredientEntities.Ingredient", "Ingredient")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.RecipeEntities.Recipe", "Recipe")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.Specification", "Specification")
                        .WithMany()
                        .HasForeignKey("SpecificationId");

                    b.Navigation("Ingredient");

                    b.Navigation("Measure");

                    b.Navigation("Recipe");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CookTheWeek.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IgredientEntities.Ingredient", b =>
                {
                    b.Navigation("RecipesIngredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.IgredientEntities.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeEntities.Recipe", b =>
                {
                    b.Navigation("RecipesIngredients");
                });

            modelBuilder.Entity("CookTheWeek.Data.Models.RecipeEntities.RecipeCategory", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
